# Generated by Django 5.2.3 on 2025-06-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='em_uso',
        ),
        migrations.RemoveField(
            model_name='material',
            name='professor_responsavel',
        ),
        migrations.AddField(
            model_name='material',
            name='validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='em_uso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='estoque_maximo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='estoque_minimo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='professor_responsavel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
